config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('cptracker/', include('cptracker.urls')),
    path('admin/', admin.site.urls),
]

cptracker/urls.py
from django.urls import path

from . import views


app_name = 'cptracker'
urlpatterns = [
    # Homepage.
    path('', views.index, name='index'),
    # Portfolios.
    path('portfolios/', views.portfolios, name='portfolios'),
    path('portfolios/<int:portfolio_id>/', views.portfolio, name='portfolio'),
    path(
        'portfolios/<int:pk>/change',
        views.PortfolioUpdateView.as_view(),
        name='change_portfolio'
    ),
    path('portfolios/add/', views.PortfolioCreateView.as_view(), name='add_portfolio'),
    # Assets.
    path(
        'portfolios/<int:pk>/asset/add',
        views.UserAssetCreateView.as_view(),
        name='add_userasset',
    ),
    path(
        'portfolios/<int:portfolio_id>/asset/<int:pk>/change',
        views.UserAssetUpdateView.as_view(),
        name='change_userasset',
    ),
]

main/urls.py
from django.urls import path

from . import views


app_name = 'main'
urlpatterns = [
    # Homepage.
    path('', views.index, name='index'),
    # Assets
    path('assets/', views.assets, name='assets'),
    path('assets/<int:asset_id>/', views.asset, name='asset'),
    path('assets/<int:pk>/change', views.AssetUpdateView.as_view(), name='change_asset'),
    path('assets/add/', views.AssetCreateView.as_view(), name='add_asset'),
]

cptracker/models.py
from django.db import models

from main.models import Asset


class Portfolio(models.Model):
    name = models.CharField(max_length=20)
    date_added = models.DateTimeField(auto_now_add=True, db_index=True)

    def __str__(self):
        return self.name

class UserAsset(models.Model):
    portfolio = models.ForeignKey(Portfolio, on_delete=models.CASCADE)
    asset = models.OneToOneField(Asset, on_delete=models.PROTECT)
    balance = models.DecimalField(max_digits=24, decimal_places=12)

    def __str__(self):
        return self.asset.short_name

main/models.py
from django.db import models


class Asset(models.Model):
    name = models.CharField(max_length=20)
    short_name = models.CharField(max_length=10)

    class AssetTypes(models.IntegerChoices):
        STOCK = 1, 'stock'
        BOND = 2, 'bond'
        CURRENCY = 3, 'currency'
        COMMODITY = 4, 'commodity'
        CRYPTOCURRENCY = 5, 'cryptocurrency'

    asset_type = models.SmallIntegerField(
        choices=AssetTypes.choices,
        default=AssetTypes.CRYPTOCURRENCY,
    )

    def __str__(self):
        return self.short_name

cptracker/forms.py
from django.forms import ModelForm, ModelChoiceField

from . import models


class PortfolioForm(ModelForm):
    class Meta:
        model = models.Portfolio
        fields = ('name',)

class UserAssetForm(ModelForm):
    class Meta:
        model = models.UserAsset
        fields = ('asset', 'balance',)
        field_classes = {'asset': ModelChoiceField}

main/forms.py
from django.forms import ModelForm

from . import models


class AssetForm(ModelForm):
    class Meta:
        model = models.Asset
        fields = ('name', 'short_name', 'asset_type')

cptracker/views.py
from typing import Any, Dict
from django.shortcuts import render
from django.views.generic.edit import CreateView, UpdateView
from django.urls import reverse_lazy

from . import models
from . import forms


def index(request):
    return render(request, 'cptracker/index.html')

def portfolios(request):
    """Extracts all portfolio records from the database."""
    portfolios =  models.Portfolio.objects.order_by('name')
    context = {'portfolios': portfolios}
    return render(request, 'cptracker/portfolios.html', context)

def portfolio(request, portfolio_id):
    portfolio = models.Portfolio.objects.get(id=portfolio_id)
    assets = models.UserAsset.objects.all()
    context = {
        'portfolio': portfolio,
        'assets': assets,
    }
    return render(request, 'cptracker/portfolio.html', context)

class PortfolioUpdateView(UpdateView):
    model = models.Portfolio
    template_name = 'cptracker/change_portfolio.html'
    form_class = forms.PortfolioForm
    success_url = reverse_lazy('cptracker:portfolios')

    def get_context_data(self, *args, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['assets'] = models.Portfolio.objects.all()
        return context

class PortfolioCreateView(CreateView):
    template_name = 'cptracker/add_portfolio.html'
    form_class = forms.PortfolioForm
    success_url = reverse_lazy('cptracker:portfolios')

class UserAssetCreateView(CreateView):
    template_name = 'cptracker/add_userasset.html'
    form_class = forms.UserAssetForm
    success_url = reverse_lazy('cptracker:portfolios')

class UserAssetUpdateView(UpdateView):
    model = models.UserAsset
    template_name = 'cptracker/change_userasset.html'
    form_class = forms.UserAssetForm
    success_url = reverse_lazy('cptracker:portfolios')

main/views.py
from typing import Any, Dict
from django.db import models
from django.shortcuts import render
from django.views.generic.edit import CreateView, UpdateView
from django.urls import reverse_lazy

from . import models
from . import forms


def index(request):
    return render(request, 'main/index.html')

def assets(request):
    assets = models.Asset.objects.order_by('short_name')
    context = {
        'assets': assets,
    }
    return render(request, 'main/assets.html', context)

def asset(request, asset_id):
    asset = models.Asset.objects.get(id=asset_id)
    context = {'asset': asset}
    return render(request, 'main/asset.html', context)

class AssetUpdateView(UpdateView):
    model = models.Asset
    template_name = 'main/change_asset.html'
    form_class = forms.AssetForm
    success_url = reverse_lazy('main:assets')

    def get_context_data(self, *args, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['assets'] = models.Asset.objects.all()
        return context

class AssetCreateView(CreateView):
    template_name = 'main/add_asset.html'
    form_class = forms.AssetForm
    success_url = reverse_lazy('main:index')

cptracker/templates/cptracker/add_portfolio.html
{% extends "layout/basic.html" %}

{% block title %}
<title>Add portfolio</title>
{% endblock title %}

{% block content %}
<h1>Add portfolio</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Add">
</form>
{% endblock content %}

cptracker/templates/cptracker/add_userasset.html
{% extends "layout/basic.html" %}

{% block title %}
<title>Add asset</title>
{% endblock title %}

{% block content %}
<h1>Add asset</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Add">
</form>
{% endblock content %}

cptracker/templates/cptracker/change_portfolio.html
{% extends "layout/basic.html" %}

{% block title %}
<title>Change portfolio</title>
{% endblock title %}

{% block content %}
<h1>Change portfolio</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Change">
</form>
{% endblock content %}

cptracker/templates/cptracker/change_userasset.html
{% extends "layout/basic.html" %}

{% block title %}
<title>Change asset</title>
{% endblock title %}

{% block content %}
<h1>Change asset</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Change">
</form>
{% endblock content %}

cptracker/templates/cptracker/index.html
{% extends "layout/basic.html" %}

{% block title %}
<title>CPTracker</title>
{% endblock title %}

{% block content %}
<p>
    This is homepage of
    Crypto Portfolio Tracker
</p>
{% endblock content %}

cptracker/templates/cptracker/portfolio.html
{% extends "layout/basic.html" %}

{% block title %}
<title>Portfolio</title>
{% endblock title %}

{% block content %}
<h1>Portfolio</h1>
<ul>
    <li>
        <h2>
            {{ portfolio.name }} - 
            <a href="{% url 'cptracker:add_userasset' portfolio.pk %}">Add asset</a>
        </h2>
        <p>{{ portfolio.date_added }}</p>
        <ul>
            {% for asset in assets %}
            <li>
                <a href="{% url 'cptracker:change_userasset' portfolio_id=portfolio.pk pk=asset.pk %}">
                    {{ asset.asset }} - {{ asset.balance }}
                </a>
            </li>
            {% empty %}
            <li>
                There are no assets...
            </li>
            {% endfor %}
        </ul>

        <a href="{% url 'cptracker:change_portfolio' portfolio.pk %}">
            Change portfolio
        </a>
    </li>
</ul>
{% endblock %}

cptracker/templates/cptracker/portfolios.html
{% extends "layout/basic.html" %}

{% block title %}
<title>Portfolios</title>
{% endblock title %}

{% block content %}
<h1>
    Portfolios
    <a href="{% url 'cptracker:add_portfolio' %}">Add portfolio</a>
</h1>
<ul>
    {% for portfolio in portfolios %}
    <li>
        <h2>
            <a href="{% url 'cptracker:portfolio' portfolio.pk %}">
                {{ portfolio.name }}
            </a>
        </h2>
        <p>{{ portfolio.date_added }}</p>
        <a href="{% url 'cptracker:change_portfolio' portfolio.pk %}">
            Change portfolio
        </a>
    </li>
    {% empty %}
    <li>
        There are no portfolios...
    </li>
    {% endfor %}
</ul>
{% endblock content %}

cptracker/templates/layout/basic.html
{% extends "main/templates/layout/basic.html" %}

main/templates/layout/basic.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        {% block title %}{% endblock title %}
    </head>
    <body>
        <p>
            <a href="{% url 'main:index' %}">Homepage</a> -
            <a href="{% url 'main:assets' %}">Assets</a>
        </p>
        <p>
            <a href="{% url 'cptracker:index' %}">Crypto Portfolio Tracker</a> -
            <a href="{% url 'cptracker:portfolios' %}">Portfolios</a>
        </p>
        {% block content %}{% endblock content %}
    </body>
</html>

main/templates/main/add_asset.html
{% extends "layout/basic.html" %}

{% block title %}
<title>Add asset</title>
{% endblock title %}

{% block content %}
<h1>Add asset</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Add">
</form>
{% endblock content %}

main/templates/main/asset.html
{% extends "layout/basic.html" %}

{% block title %}
<title>Asset</title>
{% endblock title %}

{% block content %}
<h1>Asset</h1>
<ul>
    <li>
        <h2>{{ asset.short_name }}</h2>
        <p>{{ asset.name }}</p>
        <p>{{ asset.asset_type }}</p>
        <a href="{% url 'main:change_asset' asset.pk %}">
            Change asset
        </a>
    </li>
</ul>
{% endblock %}

main/templates/main/assets.html
{% extends "layout/basic.html" %}

{% block title %}
<title>Assets</title>
{% endblock title %}

{% block content %}
<h1>
    Assets
    <a href="{% url 'main:add_asset' %}">Add asset</a>
</h1>
<ul>
    {% for asset in assets %}
    <li>
        <h2>
            <a href="{% url 'main:asset' asset.pk %}">
                {{ asset.short_name }}
            </a>
        </h2>
        <p>{{ asset.name }}</p>
        <a href="{% url 'main:change_asset' asset.pk %}">
            Change asset
        </a>
    </li>
    {% empty %}
    <li>
        There are no assets...
    </li>
    {% endfor %}
</ul>
{% endblock content %}

main/templates/main/change_asset.html
{% extends "layout/basic.html" %}

{% block title %}
<title>Change asset</title>
{% endblock title %}

{% block content %}
<h1>Change asset</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Change">
</form>
{% endblock content %}

main/templates/main/index.html
{% extends "layout/basic.html" %}

{% block title %}
<title>Homepage</title>
{% endblock title %}

{% block content %}
<p>
    This is a homepage of project
</p>
{% endblock content %}